CREATE TABLE `t_trade_order_header` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `order_id` varchar(32) NOT NULL COMMENT '订单号',
    `order_type` varchar(32) NOT NULL COMMENT '订单类型',
    `order_status` varchar(32) NOT NULL COMMENT '订单状态',
    `title` varchar(255) NOT NULL COMMENT '订单的标题',
    `customer_id` bigint(20) NOT NULL COMMENT '会员ID',
    `delivery_id` bigint(20) NOT NULL COMMENT '订单类型',
    `shop_id` varchar(64) NOT NULL COMMENT '门店ID',
    `shop_name` varchar(255) DEFAULT NULL COMMENT '门店名称',
    `erp_shop_id` varchar(64) DEFAULT NULL COMMENT '财务过账地点',
    `parent_order_id` varchar(32) DEFAULT NULL COMMENT '父单号',
    `children_order_ids` varchar(1024) DEFAULT NULL COMMENT '子订单id列表',
    `root_order_id` varchar(32) DEFAULT NULL COMMENT '根订单号',
    `order_at` datetime NOT NULL COMMENT '下单时间',
    `pay_at` datetime DEFAULT NULL COMMENT '支付时间',
    `payment_method` varchar(64) DEFAULT NULL COMMENT '支付方式',
    `paid_amt` decimal(19,2) NOT NULL DEFAULT '0.00' COMMENT '销售金额',
    `p_paid_amt` decimal(19,2) NOT NULL DEFAULT '0.00' COMMENT '用户实付商品金额',
    `f_paid_amt` decimal(19,2) NOT NULL DEFAULT '0.00' COMMENT '用户实付运费金额',
    `p_pay_amt` decimal(19,2) NOT NULL DEFAULT '0.00' COMMENT '用户应付商品金额',
    `f_pay_amt` decimal(19,2) NOT NULL DEFAULT '0.00' COMMENT '用户应付商品金额',
    `channel_id` int(11) DEFAULT NULL COMMENT '下单渠道',
    `seller_id` int(11) DEFAULT NULL COMMENT '销售业态',
    `created_at` datetime DEFAULT NULL,
    `updated_at` datetime DEFAULT NULL,
    `created_by` varchar(64) DEFAULT NULL,
    `updated_by` varchar(64) DEFAULT NULL,
    `last_updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_order_status` (`order_status`),
    KEY `idx_order_at` (`order_at`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单头表';

CREATE TABLE `t_trade_order_item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_id` varchar(36) NOT NULL COMMENT '订单编码',
  `header_id` varchar(36) NOT NULL COMMENT 'header_id',
  `shop_id` varchar(10) DEFAULT NULL COMMENT '门店编码',
  `goods_id` varchar(32) NOT NULL COMMENT '商品编码',
  `goods_name` varchar(128) DEFAULT NULL COMMENT '商品名称',
  `qty` decimal(19,4) DEFAULT '0.0000' COMMENT '数量',
  `unit` varchar(20) DEFAULT NULL COMMENT '商品单位',
  `list_price` decimal(19,10) DEFAULT '0.0000000000' COMMENT '商品单价',
  `sales_tax_code` varchar(10) DEFAULT NULL COMMENT '销项税码',
  `sales_tax` decimal(19,2) DEFAULT '0.00' COMMENT '销项税率',
  `f_sub_amt` decimal(19,2) DEFAULT '0.00' COMMENT '运费金额',
  `f_paid_sub_amt` decimal(19,2) DEFAULT '0.00' COMMENT '运费优惠后金额(用户实付)-第三方',
  `p_sub_amt` decimal(19,2) DEFAULT '0.00' COMMENT '商品金额',
  `p_paid_sub_amt` decimal(19,2) DEFAULT '0.00' COMMENT '商品优惠后金额(用户实付)-第三方',
  `sales_sub_amt` decimal(19,2) DEFAULT '0.00' COMMENT '销售收入总额（含税）',
  `sales_sub_amt_notax` decimal(19,2) DEFAULT '0.00' COMMENT '销售收入总额（不含税）',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `created_by` varchar(100) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '更新人',
  `last_updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_created_at` (`created_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单明细表';

CREATE TABLE `t_sku` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT,
 `sku_code` varchar(20) DEFAULT NULL,
 `sku_name` varchar(200) DEFAULT NULL COMMENT 'sku名',
 `sku_type` varchar(2) NOT NULL DEFAULT '1' COMMENT '商品类型：1普通 2组合码',
 `product_type` varchar(200) DEFAULT NULL COMMENT '商品类型',
 `unit` varchar(10) DEFAULT NULL COMMENT '单位',
 `spec_prop` varchar(200) DEFAULT NULL COMMENT '规格型号',
 `price` decimal(10,2) DEFAULT NULL COMMENT '价格',
 `market_price` decimal(10,2) DEFAULT NULL COMMENT '市场价',
 `sale_tax_rate` decimal(10,2) DEFAULT '0.00' COMMENT '税率',
 `sale_tax_code` varchar(10) DEFAULT NULL COMMENT '销项税率编码',
 `qty` decimal(10,2) DEFAULT '0.00' COMMENT '库存',
 `visible` int(2) NOT NULL DEFAULT '1' COMMENT '是否可见',
 `seller_id` bigint(20) DEFAULT NULL COMMENT '商家ID',
 `status` int(2) DEFAULT '1' COMMENT '状态 0:下架 1：在售',
 `tax_id` varchar(20) DEFAULT NULL COMMENT '税率分类编码',
 `category_id` varchar(20) DEFAULT NULL COMMENT '类目',
 `create_time` datetime DEFAULT NULL COMMENT '创建时间',
 `update_time` datetime DEFAULT NULL COMMENT '更新时间',
 `create_by` varchar(200) DEFAULT NULL COMMENT '创建人',
 `update_by` varchar(200) DEFAULT NULL COMMENT '更新人',
 `last_updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
 PRIMARY KEY (`id`),
 UNIQUE KEY `unique_sku_code` (`sku_code`) USING BTREE,
 KEY `idx_seller_id` (`seller_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品主数据表';

CREATE TABLE `t_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `customer_id` varchar(20) NOT NULL COMMENT '会员编码',
  `name` varchar(20) DEFAULT NULL COMMENT '用户名称',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `create_by` varchar(200) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(200) DEFAULT NULL COMMENT '更新人',
  `last_updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_customer_id` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户主数据表';





